/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateDefinitionArgs } from "./CreateDefinitionArgs";
import { UpdateDefinitionArgs } from "./UpdateDefinitionArgs";
import { DeleteDefinitionArgs } from "./DeleteDefinitionArgs";
import { DefinitionFindManyArgs } from "./DefinitionFindManyArgs";
import { DefinitionFindUniqueArgs } from "./DefinitionFindUniqueArgs";
import { Definition } from "./Definition";
import { RatingFindManyArgs } from "../../rating/base/RatingFindManyArgs";
import { Rating } from "../../rating/base/Rating";
import { DefinitionService } from "../definition.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Definition)
export class DefinitionResolverBase {
  constructor(
    protected readonly service: DefinitionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "read",
    possession: "any",
  })
  async _definitionsMeta(
    @graphql.Args() args: DefinitionFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Definition])
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "read",
    possession: "any",
  })
  async definitions(
    @graphql.Args() args: DefinitionFindManyArgs
  ): Promise<Definition[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Definition, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "read",
    possession: "own",
  })
  async definition(
    @graphql.Args() args: DefinitionFindUniqueArgs
  ): Promise<Definition | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Definition)
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "create",
    possession: "any",
  })
  async createDefinition(
    @graphql.Args() args: CreateDefinitionArgs
  ): Promise<Definition> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Definition)
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "update",
    possession: "any",
  })
  async updateDefinition(
    @graphql.Args() args: UpdateDefinitionArgs
  ): Promise<Definition | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Definition)
  @nestAccessControl.UseRoles({
    resource: "Definition",
    action: "delete",
    possession: "any",
  })
  async deleteDefinition(
    @graphql.Args() args: DeleteDefinitionArgs
  ): Promise<Definition | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Rating], { name: "ratings" })
  @nestAccessControl.UseRoles({
    resource: "Rating",
    action: "read",
    possession: "any",
  })
  async resolveFieldRatings(
    @graphql.Parent() parent: Definition,
    @graphql.Args() args: RatingFindManyArgs
  ): Promise<Rating[]> {
    const results = await this.service.findRatings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
