/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TemplateLanguageService } from "../templateLanguage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TemplateLanguageCreateInput } from "./TemplateLanguageCreateInput";
import { TemplateLanguageWhereInput } from "./TemplateLanguageWhereInput";
import { TemplateLanguageWhereUniqueInput } from "./TemplateLanguageWhereUniqueInput";
import { TemplateLanguageFindManyArgs } from "./TemplateLanguageFindManyArgs";
import { TemplateLanguageUpdateInput } from "./TemplateLanguageUpdateInput";
import { TemplateLanguage } from "./TemplateLanguage";
import { LanguageFindManyArgs } from "../../language/base/LanguageFindManyArgs";
import { Language } from "../../language/base/Language";
import { LanguageWhereUniqueInput } from "../../language/base/LanguageWhereUniqueInput";
import { TemplateFindManyArgs } from "../../template/base/TemplateFindManyArgs";
import { Template } from "../../template/base/Template";
import { TemplateWhereUniqueInput } from "../../template/base/TemplateWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TemplateLanguageControllerBase {
  constructor(
    protected readonly service: TemplateLanguageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TemplateLanguage })
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: TemplateLanguageCreateInput
  ): Promise<TemplateLanguage> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TemplateLanguage] })
  @ApiNestedQuery(TemplateLanguageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<TemplateLanguage[]> {
    const args = plainToClass(TemplateLanguageFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TemplateLanguage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: TemplateLanguageWhereUniqueInput
  ): Promise<TemplateLanguage | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TemplateLanguage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() data: TemplateLanguageUpdateInput
  ): Promise<TemplateLanguage | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TemplateLanguage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: TemplateLanguageWhereUniqueInput
  ): Promise<TemplateLanguage | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/language")
  @ApiNestedQuery(LanguageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "read",
    possession: "any",
  })
  async findManyLanguage(
    @common.Req() request: Request,
    @common.Param() params: TemplateLanguageWhereUniqueInput
  ): Promise<Language[]> {
    const query = plainToClass(LanguageFindManyArgs, request.query);
    const results = await this.service.findLanguage(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/language")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async connectLanguage(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: LanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      language: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/language")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async updateLanguage(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: LanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      language: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/language")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async disconnectLanguage(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: LanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      language: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/template")
  @ApiNestedQuery(TemplateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "any",
  })
  async findManyTemplate(
    @common.Req() request: Request,
    @common.Param() params: TemplateLanguageWhereUniqueInput
  ): Promise<Template[]> {
    const query = plainToClass(TemplateFindManyArgs, request.query);
    const results = await this.service.findTemplate(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/template")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async connectTemplate(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: TemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      template: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/template")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async updateTemplate(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: TemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      template: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/template")
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "update",
    possession: "any",
  })
  async disconnectTemplate(
    @common.Param() params: TemplateLanguageWhereUniqueInput,
    @common.Body() body: TemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      template: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
