/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LanguageService } from "../language.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LanguageCreateInput } from "./LanguageCreateInput";
import { LanguageWhereInput } from "./LanguageWhereInput";
import { LanguageWhereUniqueInput } from "./LanguageWhereUniqueInput";
import { LanguageFindManyArgs } from "./LanguageFindManyArgs";
import { LanguageUpdateInput } from "./LanguageUpdateInput";
import { Language } from "./Language";
import { ContentFindManyArgs } from "../../content/base/ContentFindManyArgs";
import { Content } from "../../content/base/Content";
import { ContentWhereUniqueInput } from "../../content/base/ContentWhereUniqueInput";
import { TemplateLanguageFindManyArgs } from "../../templateLanguage/base/TemplateLanguageFindManyArgs";
import { TemplateLanguage } from "../../templateLanguage/base/TemplateLanguage";
import { TemplateLanguageWhereUniqueInput } from "../../templateLanguage/base/TemplateLanguageWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LanguageControllerBase {
  constructor(
    protected readonly service: LanguageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Language })
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: LanguageCreateInput): Promise<Language> {
    return await this.service.create({
      data: data,
      select: {
        code: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Language] })
  @ApiNestedQuery(LanguageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Language[]> {
    const args = plainToClass(LanguageFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        code: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Language })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: LanguageWhereUniqueInput
  ): Promise<Language | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        code: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Language })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() data: LanguageUpdateInput
  ): Promise<Language | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          code: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Language })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: LanguageWhereUniqueInput
  ): Promise<Language | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          code: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/questionTemplateContents")
  @ApiNestedQuery(ContentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Content",
    action: "read",
    possession: "any",
  })
  async findManyQuestionTemplateContents(
    @common.Req() request: Request,
    @common.Param() params: LanguageWhereUniqueInput
  ): Promise<Content[]> {
    const query = plainToClass(ContentFindManyArgs, request.query);
    const results = await this.service.findQuestionTemplateContents(params.id, {
      ...query,
      select: {
        audioLink: true,
        content: true,
        contentType: true,
        createdAt: true,
        id: true,

        language: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/questionTemplateContents")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async connectQuestionTemplateContents(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: ContentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questionTemplateContents: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/questionTemplateContents")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async updateQuestionTemplateContents(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: ContentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questionTemplateContents: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/questionTemplateContents")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async disconnectQuestionTemplateContents(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: ContentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questionTemplateContents: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/templateLanguages")
  @ApiNestedQuery(TemplateLanguageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TemplateLanguage",
    action: "read",
    possession: "any",
  })
  async findManyTemplateLanguages(
    @common.Req() request: Request,
    @common.Param() params: LanguageWhereUniqueInput
  ): Promise<TemplateLanguage[]> {
    const query = plainToClass(TemplateLanguageFindManyArgs, request.query);
    const results = await this.service.findTemplateLanguages(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/templateLanguages")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async connectTemplateLanguages(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: TemplateLanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      templateLanguages: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/templateLanguages")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async updateTemplateLanguages(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: TemplateLanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      templateLanguages: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/templateLanguages")
  @nestAccessControl.UseRoles({
    resource: "Language",
    action: "update",
    possession: "any",
  })
  async disconnectTemplateLanguages(
    @common.Param() params: LanguageWhereUniqueInput,
    @common.Body() body: TemplateLanguageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      templateLanguages: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
